MODEL:
  # backbone part.
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_deeplab2_resnet_backbone"
  WEIGHTS: "../deeplab2_r50.pkl"
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  #PIXEL_MEAN: [123.675, 116.280, 103.530]
  #PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  
  # kmax part.
  # META_ARCHITECTURE: "kMaXDeepLab/"
  META_ARCHITECTURE: "VideokMaX"
  SEM_SEG_HEAD:
    NAME: "kMaXDeepLabHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 124
    # NUM_CLASSES: 133
    LOSS_WEIGHT: 1.0

  KMAX_DEEPLAB:
    SAVE_VIS_NUM: 10
    SHARE_FINAL_MATCHING: True
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 1e-5
    CLASS_WEIGHT: 3.0
    DICE_WEIGHT: 3.0
    MASK_WEIGHT: 0.3
    INSDIS_WEIGHT: 1.0
    AUX_SEMANTIC_WEIGHT: 1.0

    PIXEL_DEC:
      NAME: "kMaXPixelDecoder"
      IN_FEATURES: ["res2", "res3", "res4", "res5"]
      DEC_LAYERS: [1, 5, 1, 1]
      LAYER_TYPES: ["axial", "axial", "bottleneck", "bottleneck"]
      DEC_CHANNELS: [512, 256, 128, 64]

    TRANS_DEC:
      NAME: "kMaXTransformerDecoder"
      DEC_LAYERS: [2, 2, 2]
      NUM_OBJECT_QUERIES: 128
      IN_CHANNELS: [2048, 1024, 512] # [512 * 4, 256 * 4, 128 * 4]
      DROP_PATH_PROB: 0.2

    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: False # Save some time :)
      PANOPTIC_ON: True
      OBJECT_MASK_THRESHOLD: 0.4
      CLASS_THRESHOLD_THING: 0.5
      CLASS_THRESHOLD_STUFF: 0.5
      # OBJECT_MASK_THRESHOLD: 0.2
      # CLASS_THRESHOLD_THING: 0.3
      # CLASS_THRESHOLD_STUFF: 0.1
      REORDER_CLASS_WEIGHT: 1.0
      REORDER_MASK_WEIGHT: 1.0
      OVERLAP_THRESHOLD: 0.8
      THING_AREA_LIMIT: 0 #400 # we do not use the thing area limit for now, as the post-processing is done after resizing for now.
      STUFF_AREA_LIMIT: 0 #6400

DATASETS:
  TRAIN: ("vipseg_train_video_panoptic",)
  TEST: ("vipseg_val_video_panoptic",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.0003
  LR_SCHEDULER_NAME: "TF2WarmupPolyLR"
  MAX_ITER: 150000
  WARMUP_ITERS: 5000
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: False
  AMP:
    ENABLED: False # To be explored
INPUT:
  # IMAGE_SIZE: [897, 1601]
  # IMAGE_SIZE: [833, 1409]
  # IMAGE_SIZE: [833, 1409]
  IMAGE_SIZE: [833, 1473]
  MIN_SCALE: 0.2
  MAX_SCALE: 2.0
  # MIN_SCALE: 0.3
  # MAX_SCALE: 1.7
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "vipseg_video_panoptic"
  # MIN_SIZE_TEST: 769
  # MAX_SIZE_TEST: 1473
  MIN_SIZE_TEST: 833
  MAX_SIZE_TEST: 1473
  SAMPLING_FRAME_NUM: 2
  TEST_SAMPLING_FRAME_NUM: 2
TEST:
  EVAL_PERIOD: 0
  # EVAL_PERIOD: 1
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2