_BASE_: video_kmax_r50.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtTimm"
  WEIGHTS: "outputs/coco_video_vkmax_convnext_large_from_kmax_50k_renormalize_last/model_final.pth"
  CONVNEXT:
    IN_CHANNELS: 3
    DEPTHS: [3, 4, 30, 3]
    DIMS: [384, 768, 1536, 3072]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_large_os32.textproto#L28
    DROP_PATH_RATE: 0.4
    OUT_INDICES: [0, 1, 2, 3]
  VIDEO_KMAX:
    TEST:
      USE_CLIP_STITCHING: True
  KMAX_DEEPLAB:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.4
      CLASS_THRESHOLD_THING: 0.5
      CLASS_THRESHOLD_STUFF: 0.5
DATASETS:
  TRAIN: ("vipseg_train_video_panoptic", )
  TEST: ("vipseg_val_video_panoptic",)
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 50000
  # BACKBONE_FREEZE: True
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_valcheck_postcheck_re"
# FIND_UNUSED_PARAMETERS: True
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_valcheck_postcheck_re"
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_after_align_60k_copypast_prob1_mem_test"
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_after_align_40k_aux_seg_total_mem_test_hungar_0610"
OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_xxlarge_50k_0515"
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_after_align_40k_prev_onlystitching"
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_large_eval_on_val_cocoimg_124_after_align_40k_aux_seg_nomem_ablate"