_BASE_: video_kmax_r50.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtTimm"
  # WEIGHTS: "weights/convnext_large_22k_1k_384_new.pkl"
  # WEIGHTS: "weights/kmax_convnext_large_coco_train_unlabeled.pkl"
  # WEIGHTS: "outputs/coco_video_vkmax_convnext_large_from_kmax_150k_renormalize_alltrain_833_retrain/model_final.pth"
  WEIGHTS: "outputs/burst_vipseg_video_vkmax_convnext_xxlarge_from_openclip_25k_641/model_final.pth"
  # WEIGHTS: "outputs/coco_video_vkmax_convnext_large_from_scratch/model_0149999.pth"
  CONVNEXT:
    IN_CHANNELS: 3
    DEPTHS: [3, 4, 30, 3]
    DIMS: [384, 768, 1536, 3072]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_large_os32.textproto#L28
    DROP_PATH_RATE: 0.4
    OUT_INDICES: [0, 1, 2, 3]
  VIDEO_KMAX:
    TEST:
      USE_CLIP_STITCHING: True
  KMAX_DEEPLAB:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.4
      CLASS_THRESHOLD_THING: 0.5
      CLASS_THRESHOLD_STUFF: 0.5
DATASETS:
  TRAIN: ("vipseg_train_video_panoptic", "vipseg_val_video_panoptic")
  # TEST: ("vipseg_val_video_panoptic",)
  TEST: ("vipseg_test_video_panoptic",)
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 25000
  AMP:
    ENABLED: True # To be explored
INPUT:
  # IMAGE_SIZE: [641, 1153]
  IMAGE_SIZE: [833, 1473]
  MIN_SCALE: 0.2
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "vipseg_video_panoptic"
  MIN_SIZE_TEST: 833
  MAX_SIZE_TEST: 1473
  SAMPLING_FRAME_NUM: 2
  TEST_SAMPLING_FRAME_NUM: 2
# OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_xxlarge_from_openclip_50k_tval_641_test"
OUTPUT_DIR: "outputs/vipseg_video_vkmax_convnext_xxlarge_from_openclip_25k_after_burst_test_ensemble"
